const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),scoreEl=document.querySelector('#score'),coinsEl=document.querySelector('#coins'),hiEl=document.querySelector('#high-score'),statusEl=document.querySelector('#status'),startBtn=document.querySelector('#start'),modeEl=document.querySelector('#mode'),soundBtn=document.querySelector('#sound-toggle'),coinBtn=document.querySelector('#use-coin');
const size=18,cell=canvas.width/size,dirs={up:{x:0,y:-1},down:{x:0,y:1},left:{x:-1,y:0},right:{x:1,y:0}};
let snake,food,golden,dir,nextDir,score,coins,playing=false,timer,swipeStart,sound=true,audio,speedFactor=1,effectTimer;
const high=()=>Number(localStorage.getItem('snakebyte-high')||0),save=()=>localStorage.setItem('snakebyte-high',Math.max(high(),score));
function beep(freq,duration=.08,type='square'){if(!sound)return;audio??=new AudioContext();if(audio.state==='suspended')audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(.045,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+duration)}
function reset(){clearTimeout(effectTimer);speedFactor=1;snake=[{x:9,y:9},{x:8,y:9},{x:7,y:9}];dir=dirs.right;nextDir=dir;score=coins=0;food=spawn();golden=null;render();updateHud();statusEl.textContent='Arrow keys / WASD / swipe to move.'}
function spawn(){let p;do{p={x:Math.floor(Math.random()*size),y:Math.floor(Math.random()*size)}}while(snake?.some(s=>s.x===p.x&&s.y===p.y));return p}
function updateHud(){scoreEl.textContent=score;coinsEl.textContent=coins;hiEl.textContent=high()}
function start(){clearTimeout(timer);reset();playing=true;startBtn.textContent='RESTART';tick()}
function tick(){if(!playing)return;timer=setTimeout(()=>{move();tick()},(modeEl.value==='level'?150:120)/speedFactor)}
function applySpeed(factor,message){clearTimeout(effectTimer);speedFactor=factor;statusEl.textContent=message;effectTimer=setTimeout(()=>{speedFactor=1;if(playing)statusEl.textContent='Arrow keys / WASD / swipe to move.'},5000)}
function move(){dir=nextDir;let head={x:snake[0].x+dir.x,y:snake[0].y+dir.y};if(modeEl.value==='free'){head.x=(head.x+size)%size;head.y=(head.y+size)%size}else if(head.x<0||head.x>=size||head.y<0||head.y>=size)return over();if(snake.some(s=>s.x===head.x&&s.y===head.y))return over();snake.unshift(head);let ate=head.x===food.x&&head.y===food.y;if(ate){score+=10;beep(520);if(Math.random()<.1){coins++;beep(880,.12,'triangle')}food=spawn();if(Math.random()<.12)golden=spawn()}else snake.pop();if(golden&&head.x===golden.x&&head.y===golden.y){score+=25;golden=null;beep(740,.16,'sawtooth');applySpeed(1.25,'GOLDEN BYTE! SPEED UP')}save();updateHud();render()}
function over(){playing=false;clearTimeout(timer);beep(110,.25,'sawtooth');statusEl.textContent='GAME OVER — PRESS START';render()}
function render(){ctx.fillStyle='#10102c';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.strokeStyle='rgba(0,229,255,.08)';for(let i=1;i<size;i++){ctx.beginPath();ctx.moveTo(i*cell,0);ctx.lineTo(i*cell,canvas.height);ctx.moveTo(0,i*cell);ctx.lineTo(canvas.width,i*cell);ctx.stroke()}if(food)draw(food,'#ff2d95');if(golden)draw(golden,'#ffd300');snake?.forEach((s,i)=>draw(s,i?'#2bff88':'#00e5ff'))}
function draw(p,color){ctx.fillStyle=color;ctx.fillRect(p.x*cell+2,p.y*cell+2,cell-4,cell-4)}
function setDir(name){const d=dirs[name];if(d&&d.x!==-dir.x&&d.y!==-dir.y){nextDir=d;beep(180,.025,'triangle')}}
document.addEventListener('keydown',e=>{const map={ArrowUp:'up',w:'up',ArrowDown:'down',s:'down',ArrowLeft:'left',a:'left',ArrowRight:'right',d:'right'};if(map[e.key]){e.preventDefault();setDir(map[e.key])}});
document.querySelectorAll('[data-dir]').forEach(b=>b.addEventListener('click',()=>setDir(b.dataset.dir)));canvas.addEventListener('touchstart',e=>swipeStart=e.touches[0],{passive:true});canvas.addEventListener('touchend',e=>{if(!swipeStart)return;const t=e.changedTouches[0],dx=t.clientX-swipeStart.clientX,dy=t.clientY-swipeStart.clientY;if(Math.max(Math.abs(dx),Math.abs(dy))>20)setDir(Math.abs(dx)>Math.abs(dy)?(dx>0?'right':'left'):(dy>0?'down':'up'));swipeStart=null},{passive:true});
startBtn.addEventListener('click',start);coinBtn.addEventListener('click',()=>{if(coins<1){statusEl.textContent='NO FROG COINS';return}coins--;applySpeed(.75,'FROG COIN! SLOW DOWN');beep(300,.12,'triangle');updateHud()});soundBtn.addEventListener('click',()=>{sound=!sound;soundBtn.textContent=`SOUND: ${sound?'ON':'OFF'}`;soundBtn.setAttribute('aria-pressed',String(!sound));if(sound)beep(660)});modeEl.addEventListener('change',()=>{if(playing)start()});
reset();
